name: SPM Wasm

on:
  workflow_call:
    inputs:
      test_target_name:
        description: "Test target name"
        required: true
        type: string

env:
  RUN_TESTS: true

jobs:
  SPM-Wasm:
    name: Wasm Swift ${{ matrix.swift_version }} [${{ matrix.build_config }}]
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        swift_version: # https://github.com/swiftwasm/swift-sdk-index/tree/main/v1/builds
          - "6.0.3"
        build_config:
          - debug
          - release

    steps:
      - uses: actions/checkout@v4

      - name: Setup Swift ${{ matrix.swift_version }} WASM SDK
        id: setup-swiftwasm
        uses: swiftwasm/setup-swiftwasm@v2.1
        with:
          tag: "swift-${{ matrix.swift_version }}-RELEASE"
          target: "wasm32-unknown-wasi"

      - name: Setup wasmtime
        uses: bytecodealliance/actions/wasmtime/setup@v1
        with:
          version: "30.0.2"

      - name: Setup Wasm Runtime
        uses: wasmerio/setup-wasmer@v3
        with:
          version: "v5.0.4"

      - name: Cache SPM dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/org.swift.swiftpm
            .build/artifacts
            .build/checkouts
            .build/repositories
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Prepare
        run: |
          if [ ! -x "$(command -v jq)" ]; then
            apt update -qy
            apt install jq -qy
          fi
          TARGET_TYPES=$(swift package describe --type json | jq '.targets[].type')
          HAS_TESTS=$(echo $TARGET_TYPES | grep -q "test" && echo true || echo false)
          echo "Package has tests: $HAS_TESTS"
          echo "RUN_TESTS=$HAS_TESTS" >> $GITHUB_ENV

      - name: Build
        run: |
          swift build -c ${{ matrix.build_config }} --swift-sdk "${{ steps.setup-swiftwasm.outputs.swift-sdk-id }}" --static-swift-stdlib

      - name: Test
        if: env.RUN_TESTS == 'true'
        run: |
          swift build -c ${{ matrix.build_config }} --build-tests -Xswiftc -enable-testing --experimental-swift-sdk ${{ steps.setup-swiftwasm.outputs.swift-sdk-id }} --static-swift-stdlib
          wasmtime --dir . .build/${{ matrix.build_config }}/${{ inputs.test_target_name }}.wasm

      - name: Upload failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ github.job }}-swift_${{ matrix.swift_version }}-${{ matrix.build_config }}-${{ github.run_id }}
          path: |
            .build
          if-no-files-found: warn
          include-hidden-files: true
