name: SPM macOS

on:
  workflow_call:

env:
  RUN_TESTS: true

jobs:
  SPM-macOS:
    name: macOS Xcode ${{ matrix.config.xcode }} [${{ matrix.build_config }}]
    timeout-minutes: 30
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config: # newer versions at top
          - { os: "macos-15", xcode: "16.0" }
          - { os: "macos-14", xcode: "15.4" }
        build_config:
          - debug
          - release

    steps:
      - uses: actions/checkout@v7

      - name: Cache SPM dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm
            ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
            .build/artifacts
            .build/checkouts
            .build/repositories
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved', '**/*.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Select Xcode ${{ matrix.config.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.config.xcode }}.app

      - name: Prepare
        run: |
          TARGET_TYPES=$(swift package describe --type json | jq '.targets[].type')
          HAS_TESTS=$(echo $TARGET_TYPES | grep -q "test" && echo true || echo false)
          echo "Package has tests: $HAS_TESTS"
          echo "RUN_TESTS=$HAS_TESTS" >> $GITHUB_ENV

      - name: Build
        run: |
          swift build -c ${{ matrix.build_config }}

      - name: Test
        if: env.RUN_TESTS == 'true'
        run: |
          swift test -c ${{ matrix.build_config }}

      - name: Upload failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ github.job }}-swift_${{ matrix.config.xcode }}-${{ matrix.build_config }}-${{ github.run_id }}
          path: |
            .build
          if-no-files-found: warn
          include-hidden-files: true
