name: SPM Windows

on:
  workflow_call:

defaults:
  run: # Use powershell because bash is not supported: https://github.com/compnerd/gha-setup-swift/issues/18#issuecomment-1705524890
    shell: pwsh

env:
  RUN_TESTS: true

jobs:
  SPM-Windows:
    name: Windows Swift ${{ matrix.swift_version }} [${{ matrix.build_config }}]
    timeout-minutes: 30
    runs-on: windows-2019 # Windows SDK lower than 10.0.26100 is needed until https://github.com/swiftlang/swift/pull/79751 released!
    strategy:
      fail-fast: true
      matrix:
        swift_version: # https://github.com/swiftlang/swift/tags
          - "6.0.3"
          - "5.10.1"
        build_config:
          - debug
          - release

    steps:
      - name: Setup Swift ${{ matrix.swift_version }}
        uses: compnerd/gha-setup-swift@v0.3.0
        with:
          branch: swift-${{ matrix.swift_version }}-release
          tag: ${{ matrix.swift_version }}-RELEASE

      - uses: actions/checkout@v7

      - name: Cache SPM dependencies
        uses: actions/cache@v4
        with:
          path: | # alternative: %TEMP%\org.swift.swiftpm
            %USERPROFILE%\.swiftpm\cache
            .build\artifacts
            .build\checkouts
            .build\repositories
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Prepare
        run: |
          if (-not (Get-Command jq -ErrorAction SilentlyContinue)) {
              Write-Host "jq not found. Installing..."
              winget install --id=Jq.Jq -e
          }
          $targetTypes = swift package describe --type json | jq '.targets[].type'
          $hasTests = if ($targetTypes -match "test") { $true } else { $false }
          Write-Host "Package has tests: $hasTests"
          Add-Content -Path $env:GITHUB_ENV -Value "RUN_TESTS=$hasTests"

      - name: Build
        run: |
          swift build -c ${{ matrix.build_config }}

      - name: Test
        if: env.RUN_TESTS == 'true'
        run: |
          swift test -c ${{ matrix.build_config }}

      - name: Upload failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ github.job }}-swift_${{ matrix.swift_version }}-${{ matrix.build_config }}-${{ github.run_id }}
          path: |
            .build
          if-no-files-found: warn
          include-hidden-files: true
